removing macos notify

diff --git a/.github/workflows/macos.yml b/.github/workflows/macos.yml
--- a/.github/workflows/macos.yml
+++ b/.github/workflows/macos.yml
@@ -6,7 +6,7 @@ on:
     inputs:
       cura_conan_version:
         description: 'Cura Conan Version'
-        default: 'cura/latest@ultimaker/testing'
+        default: 'cura/latest@Aurelius-Nero/testing'
         required: true
         type: string
       conan_args:
@@ -45,7 +45,7 @@ on:
     inputs:
       cura_conan_version:
         description: 'Cura Conan Version'
-        default: 'cura/latest@ultimaker/testing'
+        default: 'cura/latest@Aurelius-Nero/testing'
         required: true
         type: string
       conan_args:
@@ -123,25 +123,25 @@ jobs:
       - name: Create the default Conan profile
         run: conan profile new default --detect --force
 
-      - name: Remove Macos keychain (Bash)
-        run: security delete-keychain signing_temp.keychain || true
+      #- name: Remove Macos keychain (Bash)
+      #  run: security delete-keychain signing_temp.keychain || true
 
-      - name: Configure Macos keychain Developer Cert(Bash)
-        id: macos-keychain-developer-cert
-        uses: apple-actions/import-codesign-certs@v1
-        with:
-          keychain-password: ${{ secrets.MACOS_KEYCHAIN_PASSWORD }}
-          p12-file-base64: ${{ secrets.MACOS_CERT_P12 }}
-          p12-password: ${{ secrets.MACOS_CERT_PASSPHRASE }}
+      #- name: Configure Macos keychain Developer Cert(Bash)
+      #  id: macos-keychain-developer-cert
+      #  uses: apple-actions/import-codesign-certs@v1
+      #  with:
+      #    keychain-password: ${{ secrets.MACOS_KEYCHAIN_PASSWORD }}
+      #    p12-file-base64: ${{ secrets.MACOS_CERT_P12 }}
+      #    p12-password: ${{ secrets.MACOS_CERT_PASSPHRASE }}
 
-      - name: Configure Macos keychain Installer Cert (Bash)
-        id: macos-keychain-installer-cert
-        uses: apple-actions/import-codesign-certs@v1
-        with:
-          keychain-password: ${{ secrets.MACOS_KEYCHAIN_PASSWORD }}
-          create-keychain: false # keychain is created in previous use of action.
-          p12-file-base64: ${{ secrets.MACOS_CERT_INSTALLER_P12 }}
-          p12-password: ${{ secrets.MACOS_CERT_PASSPHRASE }}
+      #- name: Configure Macos keychain Installer Cert (Bash)
+      #  id: macos-keychain-installer-cert
+      #  uses: apple-actions/import-codesign-certs@v1
+      #  with:
+      #    keychain-password: ${{ secrets.MACOS_KEYCHAIN_PASSWORD }}
+      #    create-keychain: false # keychain is created in previous use of action.
+      #    p12-file-base64: ${{ secrets.MACOS_CERT_INSTALLER_P12 }}
+      #    p12-password: ${{ secrets.MACOS_CERT_PASSPHRASE }}
 
       - name: Get Conan configuration
         run: |
@@ -154,20 +154,20 @@ jobs:
       - name: Create the Packages (Bash)
         run: conan install $CURA_CONAN_VERSION ${{ inputs.conan_args }} --build=missing --update -if cura_inst -g VirtualPythonEnv -o cura:enterprise=$ENTERPRISE -o cura:staging=$STAGING --json "cura_inst/conan_install_info.json"
 
-      - name: Upload the Package(s)
-        if: always()
-        run: |
-          conan upload "*" -r cura --all -c
+      #- name: Upload the Package(s)
+      #  if: always()
+      #  run: |
+      #    conan upload "*" -r cura --all -c
 
       - name: Set Environment variables for Cura (bash)
         run: |
           . ./cura_inst/bin/activate_github_actions_env.sh
           . ./cura_inst/bin/activate_github_actions_version_env.sh
 
-      - name: Unlock Macos keychain (Bash)
-        run: security unlock -p $TEMP_KEYCHAIN_PASSWORD signing_temp.keychain
-        env:
-          TEMP_KEYCHAIN_PASSWORD: ${{  steps.macos-keychain-developer-cert.outputs.keychain-password }}
+      #- name: Unlock Macos keychain (Bash)
+      #  run: security unlock -p $TEMP_KEYCHAIN_PASSWORD signing_temp.keychain
+      #  env:
+      #    TEMP_KEYCHAIN_PASSWORD: ${{  steps.macos-keychain-developer-cert.outputs.keychain-password }}
 
         # FIXME: This is a workaround to ensure that we use and pack a shared library for OpenSSL 1.1.1l. We currently compile
         #  OpenSSL statically for CPython, but our Python Dependenies (such as PyQt6) require a shared library.
@@ -280,15 +280,15 @@ jobs:
           retention-days: 5
 
 
-  notify-export:
-    if: ${{ always() }}
-    needs: [ cura-installer-create ]
-
-    uses: ultimaker/cura/.github/workflows/notify.yml@main
-    with:
-      success: ${{ contains(join(needs.*.result, ','), 'success') }}
-      success_title: "Create the Cura distributions"
-      success_body: "Installers for ${{ inputs.cura_conan_version }}"
-      failure_title: "Failed to create the Cura distributions"
-      failure_body: "Failed to create at least 1 installer for ${{ inputs.cura_conan_version }}"
-    secrets: inherit
+ # notify-export:
+ #   if: ${{ always() }}
+ #   needs: [ cura-installer-create ]
+#
+#    uses: ultimaker/cura/.github/workflows/notify.yml@main
+#    with:
+#      success: ${{ contains(join(needs.*.result, ','), 'success') }}
+#      success_title: "Create the Cura distributions"
+#      success_body: "Installers for ${{ inputs.cura_conan_version }}"
+#      failure_title: "Failed to create the Cura distributions"
+#      failure_body: "Failed to create at least 1 installer for ${{ inputs.cura_conan_version }}"
+#    secrets: inherit
